 version: '3'
 services:
   springbootdocker:
     image: caueda/oilpricing
     ports:
       - "8080:8080"
     restart: always
     healthcheck:
       test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
       interval: 30s
       timeout: 10s
       retries: 3